### ISSUE TITLE
Fix readme links and update links to Issues

### ISSUE THREAD

**Issue by santoshyadavdev** [santoshyadavdev/angular-async-local-storage#3]
https://github.com/santoshyadavdev/angular-async-local-storage/tree/main/.github/ISSUE_TEMPLATE

Issue template contains some incorrect links also README needs an update as well as the package name is changed.

**Comment by Omkar0114** [comment]
Hey @santoshyadavdev , I'm Omkar Sophomore student of Computer Science from Maharashtra, India. I'm exploring Open source now. I would like to contribute to the documentation of the project But I don't know about **Angular**. Can I work on this issue?

**Comment by santoshyadavdev** [comment]
Hey @Omkar0114 sure it doesn't require any knowledge of angular, let me know if you want to do it together with me, we can do a live stream. And work together on the issue.

**Comment by Omkar0114** [comment]
Yes sure. I'm excited to work with you! We can do it together. But I have one question, right now my semester exams are going on so is there any specific time should I have to devote to the work? or it's flexible? or can I join after my exams will end?

**Comment by santoshyadavdev** [comment]
When will you be free?

**Comment by Omkar0114** [comment]
My last paper is on 4th july, so I'll be free from 4th july after 12pm.

**Comment by santoshyadavdev** [comment]
How about 9th July?

**Comment by Omkar0114** [comment]
Yes, will be available on 9th July

**Comment by Omkar0114** [comment]
Thanks for Assigning me this issue. Really excited to work with you @santoshyadavdev 😃!

**Comment by Omkar0114** [comment]
Hey, @santoshyadavdev My exams are over now! I'll be free to work on our project. Can you give me some reference content or any docs related to a project and the issue assigned to me? It will be helpful for me to know more about the project!

**Comment by santoshyadavdev** [comment]
lets do it on sunday, can you DM your email id on Twitter?

**Comment by Omkar0114** [comment]
Ok. done DM!
